name = "ip-lookup"
main = "src/index.ts"
compatibility_date = "2022-11-05"

workers_dev = false
route = { pattern = "ip.bourboncrow.net/*", zone_name = "bourboncrow.net" }

kv_namespaces = [
	 { binding = "IP2NETWORK", id = "0346d14aac324605afeafddaa3719192", preview_id = "0346d14aac324605afeafddaa3719192" }
]
